"""Παίκτης της αγωνιστικής — the vote on who was best.

Three tables: a poll per round, the players the federation put on it, and the
votes. Candidates are chosen rather than computed, because "best" is not a
statistic — the goalkeeper who kept a village side in a game they should have
lost does not show up in a goals column.

On identity
-----------
The design asks for accounts, with a one-time code sent by SMS or email, so
that one person is one vote. There is no channel to send either from: no SMS
provider, no outbound mail. So a vote is tied to the same opaque browser token
the match predictions already use.

That is genuinely weaker. Somebody who clears their site data can vote again,
and somebody determined can vote from several browsers. It is strong enough for
what this is — a bit of Sunday fun in a federation of a few thousand people —
and it is the honest ceiling without a way to reach a phone. If an SMS provider
is ever configured, `voter_token` becomes `user_id` and everything else here
stays as it is.
"""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, ForeignKey, Index, Integer, String, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.club import Team
    from app.models.league import League
    from app.models.player import Player


class MvpPoll(Base, TimestampMixin):
    """One round's vote."""

    __tablename__ = "mvp_polls"
    __table_args__ = (
        # One poll per round per division. A second would split the vote and
        # neither result would mean anything.
        UniqueConstraint("league_id", "matchday", name="uq_mvp_poll_round"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    association_id: Mapped[int] = mapped_column(
        ForeignKey("associations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    league_id: Mapped[int] = mapped_column(
        ForeignKey("leagues.id", ondelete="CASCADE"), nullable=False, index=True
    )
    matchday: Mapped[int] = mapped_column(Integer, nullable=False)

    #: When voting stops. Null means open until somebody closes it, which is
    #: what happens when a federation forgets — so the reader is told the poll
    #: is open rather than shown a countdown that was never set.
    closes_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    created_by_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL")
    )

    league: Mapped[League] = relationship()
    candidates: Mapped[list[MvpCandidate]] = relationship(
        back_populates="poll", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<MvpPoll league={self.league_id} matchday={self.matchday}>"


class MvpCandidate(Base, TimestampMixin):
    """One player on the ballot."""

    __tablename__ = "mvp_candidates"
    __table_args__ = (
        UniqueConstraint("poll_id", "player_id", name="uq_mvp_candidate"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    poll_id: Mapped[int] = mapped_column(
        ForeignKey("mvp_polls.id", ondelete="CASCADE"), nullable=False, index=True
    )
    player_id: Mapped[int] = mapped_column(
        ForeignKey("players.id", ondelete="CASCADE"), nullable=False
    )
    #: Which club they played for in this round. Stored rather than looked up:
    #: a player can move, and the ballot should keep saying what it said.
    team_id: Mapped[int | None] = mapped_column(
        ForeignKey("teams.id", ondelete="SET NULL")
    )
    #: Why they are on the list — "3 γκολ", "κράτησε το μηδέν". Free text,
    #: because the reasons are not a fixed set and a dropdown of them would be.
    reason: Mapped[str | None] = mapped_column(String(120))

    poll: Mapped[MvpPoll] = relationship(back_populates="candidates")
    player: Mapped[Player] = relationship()
    team: Mapped[Team | None] = relationship()


class MvpVote(Base, TimestampMixin):
    """One reader's choice."""

    __tablename__ = "mvp_votes"
    __table_args__ = (
        # One per browser per poll. The same constraint the predictions use,
        # and the same limitation — see the module docstring.
        UniqueConstraint("poll_id", "voter_token", name="uq_mvp_vote"),
        Index("ix_mvp_votes_candidate", "candidate_id"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    poll_id: Mapped[int] = mapped_column(
        ForeignKey("mvp_polls.id", ondelete="CASCADE"), nullable=False, index=True
    )
    candidate_id: Mapped[int] = mapped_column(
        ForeignKey("mvp_candidates.id", ondelete="CASCADE"), nullable=False
    )
    #: Opaque, generated by the browser and stored there. Deliberately not an
    #: IP address: a village shares a handful of them, and two neighbours on
    #: the same connection are two opinions.
    voter_token: Mapped[str] = mapped_column(String(64), nullable=False)
