"""league age group

Revision ID: 011263f570a0
Revises: 59c7847348f1
Create Date: 2026-08-31 03:03:59.943491

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '011263f570a0'
down_revision: str | None = '59c7847348f1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('age_group', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'age_group')
    # ### end Alembic commands ###
