"""club access codes

Revision ID: 012af0ce236d
Revises: 3b6158978ffd
Create Date: 2026-09-23 22:56:13.100397

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '012af0ce236d'
down_revision: str | None = '3b6158978ffd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_access_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], name=op.f('fk_club_access_codes_association_id_associations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_club_access_codes_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_club_access_codes_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_access_codes'))
    )
    # Partial: a retired code keeps its club's prefix so a reissued card
    # reads the same, and only one live code may answer to it.
    op.create_index(
        'uq_club_code_prefix',
        'club_access_codes',
        ['association_id', 'prefix'],
        unique=True,
        postgresql_where=sa.text('is_active'),
    )
    op.create_index(op.f('ix_club_access_codes_association_id'), 'club_access_codes', ['association_id'], unique=False)
    op.create_index(op.f('ix_club_access_codes_team_id'), 'club_access_codes', ['team_id'], unique=False)
    op.add_column('match_events', sa.Column('created_by_code_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_match_events_created_by_code_id_club_access_codes'), 'match_events', 'club_access_codes', ['created_by_code_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_match_events_created_by_code_id_club_access_codes'), 'match_events', type_='foreignkey')
    op.drop_column('match_events', 'created_by_code_id')
    op.drop_index(op.f('ix_club_access_codes_team_id'), table_name='club_access_codes')
    op.drop_index(op.f('ix_club_access_codes_association_id'), table_name='club_access_codes')
    op.drop_table('club_access_codes')
    # ### end Alembic commands ###
