"""push preferences and quiet hours

Revision ID: 0ea059ae6499
Revises: 012af0ce236d
Create Date: 2026-09-24 11:57:05.476167

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0ea059ae6499'
down_revision: str | None = '012af0ce236d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_subscriptions', sa.Column('prefs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('push_subscriptions', sa.Column('quiet_from', sa.SmallInteger(), nullable=True))
    op.add_column('push_subscriptions', sa.Column('quiet_to', sa.SmallInteger(), nullable=True))
    op.add_column('push_subscriptions', sa.Column('utc_offset', sa.SmallInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('push_subscriptions', 'utc_offset')
    op.drop_column('push_subscriptions', 'quiet_to')
    op.drop_column('push_subscriptions', 'quiet_from')
    op.drop_column('push_subscriptions', 'prefs')
    # ### end Alembic commands ###
