"""announcements

Revision ID: 2319ace11139
Revises: 72e6f427e471
Create Date: 2026-09-23 14:10:15.908238

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2319ace11139'
down_revision: str | None = '72e6f427e471'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], name=op.f('fk_announcements_association_id_associations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements')),
    sa.UniqueConstraint('association_id', 'published_at', 'title', name='uq_announcements_identity')
    )
    op.create_index(op.f('ix_announcements_association_id'), 'announcements', ['association_id'], unique=False)
    op.create_index('ix_announcements_published', 'announcements', ['association_id', 'published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_announcements_published', table_name='announcements')
    op.drop_index(op.f('ix_announcements_association_id'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
