"""platform sponsors and sponsor stats

Revision ID: 2360ce545f20
Revises: 5c9b02c2d27c
Create Date: 2026-09-26 03:06:03.725978

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2360ce545f20'
down_revision: str | None = '5c9b02c2d27c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('logo_png_url', sa.String(length=255), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('placements', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], name=op.f('fk_platform_sponsors_association_id_associations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_sponsors'))
    )
    op.create_index('ix_platform_sponsors_association_dates', 'platform_sponsors', ['association_id', 'ends_on'], unique=False)
    op.create_index(op.f('ix_platform_sponsors_association_id'), 'platform_sponsors', ['association_id'], unique=False)
    op.create_table('sponsor_daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('views', sa.Integer(), server_default='0', nullable=False),
    sa.Column('clicks', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], name=op.f('fk_sponsor_daily_stats_association_id_associations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sponsor_daily_stats')),
    sa.UniqueConstraint('kind', 'ref_id', 'day', name='uq_sponsor_daily_stats')
    )
    op.create_index(op.f('ix_sponsor_daily_stats_association_id'), 'sponsor_daily_stats', ['association_id'], unique=False)
    op.add_column('sponsors', sa.Column('starts_on', sa.Date(), nullable=True))
    op.add_column('sponsors', sa.Column('ends_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsors', 'ends_on')
    op.drop_column('sponsors', 'starts_on')
    op.drop_index(op.f('ix_sponsor_daily_stats_association_id'), table_name='sponsor_daily_stats')
    op.drop_table('sponsor_daily_stats')
    op.drop_index(op.f('ix_platform_sponsors_association_id'), table_name='platform_sponsors')
    op.drop_index('ix_platform_sponsors_association_dates', table_name='platform_sponsors')
    op.drop_table('platform_sponsors')
    # ### end Alembic commands ###
