"""players, stats and suspensions

Revision ID: 2faa4946ac44
Revises: 011263f570a0
Create Date: 2026-09-02 22:49:35.535513

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2faa4946ac44'
down_revision: str | None = '011263f570a0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], name=op.f('fk_players_association_id_associations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('association_id', 'external_id', name='uq_players_external'),
    sa.UniqueConstraint('association_id', 'slug', name='uq_players_slug')
    )
    op.create_index(op.f('ix_players_association_id'), 'players', ['association_id'], unique=False)
    op.create_index(op.f('ix_players_external_id'), 'players', ['external_id'], unique=False)
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('own_goals', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_player_stats_league_id_leagues'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_stats_player_id_players'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_player_stats_team_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_stats')),
    sa.UniqueConstraint('league_id', 'player_id', name='uq_player_stats')
    )
    op.create_index(op.f('ix_player_stats_league_id'), 'player_stats', ['league_id'], unique=False)
    op.create_index(op.f('ix_player_stats_player_id'), 'player_stats', ['player_id'], unique=False)
    op.create_table('player_suspensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('matchday', sa.Integer(), nullable=True),
    sa.Column('decided_on', sa.Date(), nullable=True),
    sa.Column('matches', sa.Integer(), nullable=False),
    sa.Column('fixture', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_player_suspensions_league_id_leagues'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_player_suspensions_match_id_matches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_suspensions_player_id_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_suspensions')),
    sa.UniqueConstraint('league_id', 'player_id', 'matchday', 'decided_on', name='uq_player_suspensions')
    )
    op.create_index(op.f('ix_player_suspensions_league_id'), 'player_suspensions', ['league_id'], unique=False)
    op.create_index(op.f('ix_player_suspensions_player_id'), 'player_suspensions', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_suspensions_player_id'), table_name='player_suspensions')
    op.drop_index(op.f('ix_player_suspensions_league_id'), table_name='player_suspensions')
    op.drop_table('player_suspensions')
    op.drop_index(op.f('ix_player_stats_player_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_league_id'), table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_index(op.f('ix_players_external_id'), table_name='players')
    op.drop_index(op.f('ix_players_association_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
