"""match log baseline

Revision ID: 3a02fc95d6e9
Revises: 2360ce545f20
Create Date: 2026-09-27 21:01:34.648168

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3a02fc95d6e9'
down_revision: str | None = '2360ce545f20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('log_baseline', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'log_baseline')
    # ### end Alembic commands ###
