"""push subscriptions

Revision ID: 3b6158978ffd
Revises: 2319ace11139
Create Date: 2026-09-23 16:07:31.509554

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3b6158978ffd'
down_revision: str | None = '2319ace11139'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=600), nullable=False),
    sa.Column('p256dh', sa.String(length=200), nullable=False),
    sa.Column('auth', sa.String(length=100), nullable=False),
    sa.Column('team_slug', sa.String(length=120), nullable=False),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], name=op.f('fk_push_subscriptions_association_id_associations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_subscriptions')),
    sa.UniqueConstraint('endpoint', 'team_slug', name='uq_push_endpoint_team')
    )
    op.create_index(op.f('ix_push_subscriptions_association_id'), 'push_subscriptions', ['association_id'], unique=False)
    op.create_index('ix_push_team', 'push_subscriptions', ['association_id', 'team_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_push_team', table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_association_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
