"""scrape runs and team aliases

Revision ID: 59c7847348f1
Revises: 746bfc04b412
Create Date: 2026-08-27 17:15:01.086436

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '59c7847348f1'
down_revision: str | None = '746bfc04b412'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('source_key', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'partial', 'failed', name='scraperunstatus', native_enum=False, length=16), nullable=False),
    sa.Column('http_requests', sa.Integer(), nullable=False),
    sa.Column('matches_created', sa.Integer(), nullable=False),
    sa.Column('matches_updated', sa.Integer(), nullable=False),
    sa.Column('matches_unchanged', sa.Integer(), nullable=False),
    sa.Column('matches_deferred', sa.Integer(), nullable=False),
    sa.Column('teams_created', sa.Integer(), nullable=False),
    sa.Column('conflicts_opened', sa.Integer(), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], name=op.f('fk_scrape_runs_association_id_associations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_scrape_runs_league_id_leagues'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_runs'))
    )
    op.create_index(op.f('ix_scrape_runs_association_id'), 'scrape_runs', ['association_id'], unique=False)
    op.create_index('ix_scrape_runs_association_started', 'scrape_runs', ['association_id', 'started_at'], unique=False)
    op.create_table('team_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=160), nullable=False),
    sa.Column('normalized', sa.String(length=160), nullable=False),
    sa.Column('source_key', sa.String(length=40), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], name=op.f('fk_team_aliases_association_id_associations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_team_aliases_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_aliases_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_aliases')),
    sa.UniqueConstraint('association_id', 'normalized', name='uq_team_aliases_assoc_normalized')
    )
    op.create_index(op.f('ix_team_aliases_association_id'), 'team_aliases', ['association_id'], unique=False)
    op.create_index(op.f('ix_team_aliases_normalized'), 'team_aliases', ['normalized'], unique=False)
    op.create_index(op.f('ix_team_aliases_team_id'), 'team_aliases', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_aliases_team_id'), table_name='team_aliases')
    op.drop_index(op.f('ix_team_aliases_normalized'), table_name='team_aliases')
    op.drop_index(op.f('ix_team_aliases_association_id'), table_name='team_aliases')
    op.drop_table('team_aliases')
    op.drop_index('ix_scrape_runs_association_started', table_name='scrape_runs')
    op.drop_index(op.f('ix_scrape_runs_association_id'), table_name='scrape_runs')
    op.drop_table('scrape_runs')
    # ### end Alembic commands ###
