"""mvp polls

Revision ID: 65bae4f07b7b
Revises: 0ea059ae6499
Create Date: 2026-09-24 12:08:43.297388

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '65bae4f07b7b'
down_revision: str | None = '0ea059ae6499'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mvp_polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('matchday', sa.Integer(), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], name=op.f('fk_mvp_polls_association_id_associations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_mvp_polls_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_mvp_polls_league_id_leagues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mvp_polls')),
    sa.UniqueConstraint('league_id', 'matchday', name='uq_mvp_poll_round')
    )
    op.create_index(op.f('ix_mvp_polls_association_id'), 'mvp_polls', ['association_id'], unique=False)
    op.create_index(op.f('ix_mvp_polls_league_id'), 'mvp_polls', ['league_id'], unique=False)
    op.create_table('mvp_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_mvp_candidates_player_id_players'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['mvp_polls.id'], name=op.f('fk_mvp_candidates_poll_id_mvp_polls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_mvp_candidates_team_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mvp_candidates')),
    sa.UniqueConstraint('poll_id', 'player_id', name='uq_mvp_candidate')
    )
    op.create_index(op.f('ix_mvp_candidates_poll_id'), 'mvp_candidates', ['poll_id'], unique=False)
    op.create_table('mvp_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('voter_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['mvp_candidates.id'], name=op.f('fk_mvp_votes_candidate_id_mvp_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['mvp_polls.id'], name=op.f('fk_mvp_votes_poll_id_mvp_polls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mvp_votes')),
    sa.UniqueConstraint('poll_id', 'voter_token', name='uq_mvp_vote')
    )
    op.create_index('ix_mvp_votes_candidate', 'mvp_votes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_mvp_votes_poll_id'), 'mvp_votes', ['poll_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mvp_votes_poll_id'), table_name='mvp_votes')
    op.drop_index('ix_mvp_votes_candidate', table_name='mvp_votes')
    op.drop_table('mvp_votes')
    op.drop_index(op.f('ix_mvp_candidates_poll_id'), table_name='mvp_candidates')
    op.drop_table('mvp_candidates')
    op.drop_index(op.f('ix_mvp_polls_league_id'), table_name='mvp_polls')
    op.drop_index(op.f('ix_mvp_polls_association_id'), table_name='mvp_polls')
    op.drop_table('mvp_polls')
    # ### end Alembic commands ###
