"""match event client id

Revision ID: 72e6f427e471
Revises: 7d036b389df5
Create Date: 2026-09-23 12:23:36.363689

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '72e6f427e471'
down_revision: str | None = '7d036b389df5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_events', sa.Column('client_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_match_events_client_id', 'match_events', ['client_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_match_events_client_id', 'match_events', type_='unique')
    op.drop_column('match_events', 'client_id')
    # ### end Alembic commands ###
