"""initial multi-tenant schema

Revision ID: 746bfc04b412
Revises: 
Create Date: 2026-08-27 16:07:39.767832

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '746bfc04b412'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('short_name', sa.String(length=40), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('scraper_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('primary_color', sa.String(length=9), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_associations')),
    sa.UniqueConstraint('slug', name=op.f('uq_associations_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('role', sa.Enum('admin', 'editor', name='userrole', native_enum=False, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('association_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], name=op.f('fk_audit_log_association_id_associations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_association_id'), 'audit_log', ['association_id'], unique=False)
    op.create_index('ix_audit_log_created', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('short_name', sa.String(length=60), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('surface', sa.Enum('grass', 'artificial', 'dirt', name='fieldsurface', native_enum=False, length=20), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('has_floodlights', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], name=op.f('fk_fields_association_id_associations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fields')),
    sa.UniqueConstraint('association_id', 'slug', name='uq_fields_association_slug')
    )
    op.create_index(op.f('ix_fields_association_id'), 'fields', ['association_id'], unique=False)
    op.create_index(op.f('ix_fields_external_id'), 'fields', ['external_id'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], name=op.f('fk_seasons_association_id_associations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons')),
    sa.UniqueConstraint('association_id', 'slug', name='uq_seasons_association_slug')
    )
    op.create_index('ix_seasons_association_current', 'seasons', ['association_id', 'is_current'], unique=False)
    op.create_index(op.f('ix_seasons_association_id'), 'seasons', ['association_id'], unique=False)
    op.create_table('user_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('can_edit_live', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], name=op.f('fk_user_associations_association_id_associations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_associations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_associations')),
    sa.UniqueConstraint('user_id', 'association_id', name='uq_user_associations_pair')
    )
    op.create_index(op.f('ix_user_associations_association_id'), 'user_associations', ['association_id'], unique=False)
    op.create_index(op.f('ix_user_associations_user_id'), 'user_associations', ['user_id'], unique=False)
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('short_name', sa.String(length=60), nullable=True),
    sa.Column('kind', sa.Enum('championship', 'cup', 'playoff', name='leaguekind', native_enum=False, length=20), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=60), nullable=True),
    sa.Column('total_matchdays', sa.Integer(), nullable=True),
    sa.Column('current_matchday', sa.Integer(), nullable=True),
    sa.Column('points_per_win', sa.Integer(), nullable=False),
    sa.Column('points_per_draw', sa.Integer(), nullable=False),
    sa.Column('zones', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], name=op.f('fk_leagues_association_id_associations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_leagues_season_id_seasons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leagues')),
    sa.UniqueConstraint('association_id', 'season_id', 'slug', name='uq_leagues_assoc_season_slug')
    )
    op.create_index(op.f('ix_leagues_association_id'), 'leagues', ['association_id'], unique=False)
    op.create_index('ix_leagues_association_season', 'leagues', ['association_id', 'season_id'], unique=False)
    op.create_index(op.f('ix_leagues_external_id'), 'leagues', ['external_id'], unique=False)
    op.create_index(op.f('ix_leagues_season_id'), 'leagues', ['season_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('short_name', sa.String(length=60), nullable=True),
    sa.Column('initials', sa.String(length=4), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('primary_color', sa.String(length=9), nullable=True),
    sa.Column('secondary_color', sa.String(length=9), nullable=True),
    sa.Column('home_field_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], name=op.f('fk_teams_association_id_associations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['home_field_id'], ['fields.id'], name=op.f('fk_teams_home_field_id_fields'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('association_id', 'slug', name='uq_teams_association_slug')
    )
    op.create_index(op.f('ix_teams_association_id'), 'teams', ['association_id'], unique=False)
    op.create_index('ix_teams_association_name', 'teams', ['association_id', 'name'], unique=False)
    op.create_index(op.f('ix_teams_external_id'), 'teams', ['external_id'], unique=False)
    op.create_table('league_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('points_deduction', sa.Integer(), nullable=False),
    sa.Column('has_withdrawn', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_league_teams_league_id_leagues'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_league_teams_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_league_teams')),
    sa.UniqueConstraint('league_id', 'team_id', name='uq_league_teams_league_team')
    )
    op.create_index(op.f('ix_league_teams_league_id'), 'league_teams', ['league_id'], unique=False)
    op.create_index(op.f('ix_league_teams_team_id'), 'league_teams', ['team_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('matchday', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'live', 'halftime', 'finished', 'postponed', 'cancelled', 'awarded', name='matchstatus', native_enum=False, length=20), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('home_score_ht', sa.Integer(), nullable=True),
    sa.Column('away_score_ht', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('referee', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('data_source', sa.Enum('scraper', 'manual_live', 'manual_confirmed', name='datasource', native_enum=False, length=20), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('last_manual_edit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('home_team_id <> away_team_id', name=op.f('ck_matches_teams_differ')),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_matches_away_team_id_teams'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_matches_field_id_fields'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_matches_home_team_id_teams'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_matches_league_id_leagues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
    sa.UniqueConstraint('league_id', 'external_id', name='uq_matches_league_external')
    )
    op.create_index(op.f('ix_matches_away_team_id'), 'matches', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_matches_home_team_id'), 'matches', ['home_team_id'], unique=False)
    op.create_index('ix_matches_kickoff', 'matches', ['kickoff_at'], unique=False)
    op.create_index(op.f('ix_matches_league_id'), 'matches', ['league_id'], unique=False)
    op.create_index('ix_matches_league_matchday', 'matches', ['league_id', 'matchday'], unique=False)
    op.create_index('ix_matches_live', 'matches', ['is_live'], unique=False)
    op.create_table('standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('previous_position', sa.Integer(), nullable=True),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('drawn', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('goal_difference', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(length=10), nullable=True),
    sa.Column('zone', sa.Enum('promotion', 'promotion_playoff', 'relegation_playoff', 'relegation', name='standingzone', native_enum=False, length=24), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_standings_league_id_leagues'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_standings_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standings')),
    sa.UniqueConstraint('league_id', 'team_id', name='uq_standings_league_team')
    )
    op.create_index(op.f('ix_standings_league_id'), 'standings', ['league_id'], unique=False)
    op.create_index('ix_standings_league_position', 'standings', ['league_id', 'position'], unique=False)
    op.create_index(op.f('ix_standings_team_id'), 'standings', ['team_id'], unique=False)
    op.create_table('scrape_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('scraped_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved_manual', 'resolved_scraper', name='conflictstatus', native_enum=False, length=24), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_scrape_conflicts_match_id_matches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_scrape_conflicts_resolved_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_conflicts'))
    )
    op.create_index(op.f('ix_scrape_conflicts_match_id'), 'scrape_conflicts', ['match_id'], unique=False)
    op.create_index('ix_scrape_conflicts_status', 'scrape_conflicts', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scrape_conflicts_status', table_name='scrape_conflicts')
    op.drop_index(op.f('ix_scrape_conflicts_match_id'), table_name='scrape_conflicts')
    op.drop_table('scrape_conflicts')
    op.drop_index(op.f('ix_standings_team_id'), table_name='standings')
    op.drop_index('ix_standings_league_position', table_name='standings')
    op.drop_index(op.f('ix_standings_league_id'), table_name='standings')
    op.drop_table('standings')
    op.drop_index('ix_matches_live', table_name='matches')
    op.drop_index('ix_matches_league_matchday', table_name='matches')
    op.drop_index(op.f('ix_matches_league_id'), table_name='matches')
    op.drop_index('ix_matches_kickoff', table_name='matches')
    op.drop_index(op.f('ix_matches_home_team_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_away_team_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_league_teams_team_id'), table_name='league_teams')
    op.drop_index(op.f('ix_league_teams_league_id'), table_name='league_teams')
    op.drop_table('league_teams')
    op.drop_index(op.f('ix_teams_external_id'), table_name='teams')
    op.drop_index('ix_teams_association_name', table_name='teams')
    op.drop_index(op.f('ix_teams_association_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_leagues_season_id'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_external_id'), table_name='leagues')
    op.drop_index('ix_leagues_association_season', table_name='leagues')
    op.drop_index(op.f('ix_leagues_association_id'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_user_associations_user_id'), table_name='user_associations')
    op.drop_index(op.f('ix_user_associations_association_id'), table_name='user_associations')
    op.drop_table('user_associations')
    op.drop_index(op.f('ix_seasons_association_id'), table_name='seasons')
    op.drop_index('ix_seasons_association_current', table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_fields_external_id'), table_name='fields')
    op.drop_index(op.f('ix_fields_association_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_index('ix_audit_log_created', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_association_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('associations')
    # ### end Alembic commands ###
