"""scrape run people counters

Revision ID: 78c45d8f409a
Revises: 2faa4946ac44
Create Date: 2026-09-02 22:52:40.541995

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '78c45d8f409a'
down_revision: str | None = '2faa4946ac44'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_runs', sa.Column('players_created', sa.Integer(), nullable=False))
    op.add_column('scrape_runs', sa.Column('stats_rows', sa.Integer(), nullable=False))
    op.add_column('scrape_runs', sa.Column('suspensions', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_runs', 'suspensions')
    op.drop_column('scrape_runs', 'stats_rows')
    op.drop_column('scrape_runs', 'players_created')
    # ### end Alembic commands ###
