"""match events

Revision ID: 7d036b389df5
Revises: 7597d050b0f4
Create Date: 2026-09-23 11:25:38.840424

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7d036b389df5'
down_revision: str | None = '7597d050b0f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('goal', 'penalty_goal', 'own_goal', 'penalty_miss', 'yellow', 'second_yellow', 'red', 'substitution', 'kickoff', 'halftime', 'second_half', 'fulltime', 'note', name='matcheventkind', native_enum=False, length=20), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(length=160), nullable=True),
    sa.Column('related_player_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_match_events_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_events_match_id_matches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_match_events_player_id_players'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_player_id'], ['players.id'], name=op.f('fk_match_events_related_player_id_players'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_match_events_team_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_events'))
    )
    op.create_index(op.f('ix_match_events_match_id'), 'match_events', ['match_id'], unique=False)
    op.create_index('ix_match_events_match_minute', 'match_events', ['match_id', 'minute'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_match_events_match_minute', table_name='match_events')
    op.drop_index(op.f('ix_match_events_match_id'), table_name='match_events')
    op.drop_table('match_events')
    # ### end Alembic commands ###
