"""anonymous analytics

Revision ID: c826575a73c3
Revises: 3a02fc95d6e9
Create Date: 2026-09-27 21:54:21.552097

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c826575a73c3'
down_revision: str | None = '3a02fc95d6e9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('visitor', sa.String(length=16), nullable=False),
    sa.Column('props', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], name=op.f('fk_analytics_events_association_id_associations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_events'))
    )
    op.create_index('ix_analytics_events_association_at', 'analytics_events', ['association_id', 'at', 'name'], unique=False)
    op.create_table('page_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('route', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=160), nullable=True),
    sa.Column('visitor', sa.String(length=16), nullable=False),
    sa.Column('referrer_host', sa.String(length=120), nullable=True),
    sa.Column('utm_source', sa.String(length=80), nullable=True),
    sa.Column('utm_medium', sa.String(length=80), nullable=True),
    sa.Column('utm_campaign', sa.String(length=120), nullable=True),
    sa.Column('device', sa.String(length=10), nullable=True),
    sa.Column('browser', sa.String(length=24), nullable=True),
    sa.Column('os', sa.String(length=24), nullable=True),
    sa.Column('lang', sa.String(length=12), nullable=True),
    sa.Column('viewport_width', sa.SmallInteger(), nullable=True),
    sa.Column('dark', sa.Boolean(), nullable=True),
    sa.Column('installed', sa.Boolean(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('scroll_pct', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['association_id'], ['associations.id'], name=op.f('fk_page_views_association_id_associations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_views'))
    )
    op.create_index('ix_page_views_association_at', 'page_views', ['association_id', 'at'], unique=False)
    op.create_index('ix_page_views_route', 'page_views', ['association_id', 'route'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_page_views_route', table_name='page_views')
    op.drop_index('ix_page_views_association_at', table_name='page_views')
    op.drop_table('page_views')
    op.drop_index('ix_analytics_events_association_at', table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
